### ISSUE TITLE
[Request] Full document's height capture

### ISSUE THREAD

**Issue by RichardDern** [FireFart/gochro#1]
Hi, 

I was wondering if there is a way to get a capture of the whole URL, not just cropped to provided height, or if it's going to be implemented.

Otherwise, thanks, it works perfectly !

**Comment by FireFart** [comment]
Hi,
not that I'm aware of. You could only set the height to a big value but the screenshot commandline parameter works different than the dev tools screenshot function it seems :/

**Comment by RichardDern** [comment]
Bummer. Thanks anyway for the reply !
