### ISSUE TITLE
Args by url parameters.

### ISSUE THREAD

**Issue by KrejcirD** [firefart/gochro#19]
I have an issue where i need to pass `--print-to-pdf-no-header`  to Chromium,
It would be great if it was possible to pass values to args via  the request URL.
Something like: `/html2pdf?w=1024&h=768&print-to-pdf-no-header=true`

https://github.com/firefart/gochro/blob/b5c07923e300f79a3660d538d57c433b13665869/main.go#L142

**Comment by petrprikryl** [comment]
I think that it would be better to not whitelisting the args and rather pass it to chrome. It would be much more flexible.

**Comment by firefart** [comment]
thanks! Did not know about the parameter so I implemented it by default so the temp filename is now shown in the footer.
